const { description } = require("../../package")

module.exports = {
  extendMarkdown: (md) => {
    md.use(require("markdown-it-footnote"))
  },

  /**
   * Ref：https://v1.vuepress.vuejs.org/config/#title
   */
  title: "The Society of Mind",
  /**
   * Ref：https://v1.vuepress.vuejs.org/config/#description
   */
  description: description,

  /**
   * Extra tags to be injected to the page HTML `<head>`
   *
   * ref：https://v1.vuepress.vuejs.org/config/#head
   */
  head: [
    ["meta", { name: "theme-color", content: "#3eaf7c" }],
    ["meta", { name: "apple-mobile-web-app-capable", content: "yes" }],
    [
      "meta",
      { name: "apple-mobile-web-app-status-bar-style", content: "black" },
    ],
  ],

  /**
   * Theme configuration, here is the default theme configuration for VuePress.
   *
   * ref：https://v1.vuepress.vuejs.org/theme/default-theme-config.html
   */
  themeConfig: {
    repo: "",
    editLinks: false,
    docsDir: "",
    editLinkText: "",
    lastUpdated: false,
    algolia: {
      appId: "B7YHEYSK1Q",
      apiKey: "830068331e7c4c30802776f15ac67c98",
      indexName: "som",
    },
    nav: [
      {
        text: "The Society of Mind",
        link: "/text/1_prologue",
      },
      {
        text: "SOM Glossary",
        link: "/glossary/",
      },
      {
        text: "The Emotion Machine",
        link: "/em/1_1",
      },
    ],
    sidebar: {
      "/em/": [
        {
          title: `1 Falling in Love`,
          path: `/em/1_1`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`1_1`, `1.1 Falling in Love`],
            [`1_2`, `1.2 The Sea Of Mental Mysteries`],
            [`1_3`, `1.3 Moods and Emotions`],
            [`1_4`, `1.4 Infant Emotions`],
            [`1_5`, `1.5 Seeing a Mind as a Cloud of Resources`],
            [`1_6`, `1.6 Adult Emotions`],
            [`1_7`, `1.7 Emotion Cascades`],
            [`1_8`, `1.8 Questions`],
          ],
        },
        {
          title: `2 Attachments and Goals`,
          path: `/em/2_1`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`2_1`, `2.1 Playing with Mud`],
            [`2_2`, `2.2 Attachments and Goals`],
            [`2_3`, `2.3 Imprimers`],
            [`2_4`, `2.4 Attachment-Learning Elevates Goals`],
            [`2_5`, `2.5 Learning and pleasure`],
            [`2_6`, `2.6 Conscience, Values and Self-Ideals`],
            [`2_7`, `2.7 Attachments of Infants and Animals`],
            [`2_8`, `2.8 Who are our Imprimers?`],
            [`2_9`, `2.9 Self-Models and Self-Consistency`],
            [`2_10`, `2.10  Public Imprimers`],
            [`2_11`, `2.11 Playing with Mud`],
          ],
        },
        {
          title: `3 From Pain to Suffering`,
          path: `/em/3_1`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`3_1`, `3.1 Being in Pain`],
            [`3_2`, `3.2 Prolonged Pain leads to Cascades`],
            [`3_3`, `3.3 Feeling, Hurting, and Suffering`],
            [`3_4`, `3.4 Overriding Pain`],
            [`3_5`, `3.5 Correctors, Suppressors, and Censors`],
            [`3_6`, `3.6 The Freudian Sandwich`],
            [`3_7`, `3.7 Controlling our Moods and Dispositions`],
            [`3_8`, `3.8 Emotional Exploitation`],
          ],
        },
        {
          title: `part 4`,
          path: `/em/4_1`,
          collapsable: false,
          sidebarDepth: 2,
        },
        {
          title: `part 5`,
          path: `/em/5_1`,
          collapsable: false,
          sidebarDepth: 2,
        },
        {
          title: `part 6`,
          path: `/em/6_1`,
          collapsable: false,
          sidebarDepth: 2,
        },
        {
          title: `part 7`,
          path: `/em/7_1`,
          collapsable: false,
          sidebarDepth: 2,
        },
        {
          title: `part 8`,
          path: `/em/8_1`,
          collapsable: false,
          sidebarDepth: 2,
        },
        {
          title: `9 The Self`,
          path: `/em/9_1`,
          collapsable: false,
          sidebarDepth: 2,
        },
      ],

      "/text/": [
        {
          title: `1 PROLOGUE`,
          path: `/text/1_prologue/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`1_1_the_agents_of_the_mind`, `1.1 THE AGENTS OF THE MIND`],
            [`1_2_the_mind_and_the_brain`, `1.2 THE MIND AND THE BRAIN`],
            [`1_3_the_society_of_mind`, `1.3 THE SOCIETY OF MIND`],
            [`1_4_the_world_of_blocks`, `1.4 THE WORLD OF BLOCKS`],
          ],
        },
        {
          title: `2 WHOLES AND PARTS`,
          path: `/text/2_wholes_and_parts/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [
              `2_1_components_and_connections`,
              `2.1 COMPONENTS AND CONNECTIONS`,
            ],
            [
              `2_2_novelists_and_reductionists`,
              `2.2 NOVELISTS AND REDUCTIONISTS`,
            ],
            [`2_3_parts_and_wholes`, `2.3 PARTS AND WHOLES`],
            [`2_4_holes_and_parts`, `2.4 HOLES AND PARTS`],
            [`2_5_easy_things_are_hard`, `2.5 EASY THINGS ARE HARD`],
            [`2_6_are_people_machines`, `2.6 ARE PEOPLE MACHINES`],
          ],
        },
        {
          title: `3 CONFLICT AND COMPROMISE`,
          path: `/text/3_conflict_and_compromise/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`3_1_conflict`, `3.1 CONFLICT`],
            [`3_2_noncompromise`, `3.2 NONCOMPROMISE`],
            [`3_3_hierarchies`, `3.3 HIERARCHIES`],
            [`3_4_heterarchies`, `3.4 HETERARCHIES`],
            [`3_5_destructiveness`, `3.5 DESTRUCTIVENESS`],
            [
              `3_6_pain_and_pleasure_simplified`,
              `3.6 PAIN AND PLEASURE SIMPLIFIED`,
            ],
          ],
        },
        {
          title: `4 THE SELF`,
          path: `/text/4_the_self/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`4_1_the_self`, `4.1 THE SELF`],
            [`4_2_one_self_or_many`, `4.2 ONE SELF OR MANY`],
            [`4_3_the_soul`, `4.3 THE SOUL`],
            [`4_4_the_conservative_self`, `4.4 THE CONSERVATIVE SELF`],
            [`4_5_exploitation`, `4.5 EXPLOITATION`],
            [`4_6_self-control`, `4.6 SELF-CONTROL`],
            [`4_7_long-range_plans`, `4.7 LONG-RANGE PLANS`],
            [`4_8_ideals`, `4.8 IDEALS`],
          ],
        },
        {
          title: `5 INDIVIDUALITY`,
          path: `/text/5_individuality/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`5_individuality`, `5 INDIVIDUALITY`],
            [`5_1_circular_causality`, `5.1 CIRCULAR CAUSALITY`],
            [`5_2_unanswerable_questions`, `5.2 UNANSWERABLE QUESTIONS`],
            [`5_3_the_remote-control_self`, `5.3 THE REMOTE-CONTROL SELF`],
            [`5_4_personal_identity`, `5.4 PERSONAL IDENTITY`],
            [`5_5_fashion_and_style`, `5.5 FASHION AND STYLE`],
            [`5_6_traits`, `5.6 TRAITS`],
            [`5_7_permanent_identity`, `5.7 PERMANENT IDENTITY`],
          ],
        },
        {
          title: `6 INSIGHT AND INTROSPECTION`,
          path: `/text/6_insight_and_introspection/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`6_1_consciousness`, `6.1 CONSCIOUSNESS`],
            [`6_2_signals_and_signs`, `6.2 SIGNALS AND SIGNS`],
            [`6_3_thought-experiments`, `6.3 THOUGHT-EXPERIMENTS`],
            [`6_4_b-brains`, `6.4 B-BRAINS`],
            [`6_5_frozen_reflection`, `6.5 FROZEN REFLECTION`],
            [`6_6_momentary_mental_time`, `6.6 MOMENTARY MENTAL TIME`],
            [`6_7_the_causal_now`, `6.7 THE CAUSAL NOW`],
            [`6_8_thinking_without_thinking`, `6.8 THINKING WITHOUT THINKING`],
            [`6_9_heads_in_the_clouds`, `6.9 HEADS IN THE CLOUDS`],
            [`6_10_worlds_out_of_mind`, `6.10 WORLDS OUT OF MIND`],
            [`6_11_in-sight`, `6.11 IN-SIGHT`],
            [`6_12_internal_communication`, `6.12 INTERNAL COMMUNICATION`],
            [
              `6_13_self-knowledge_is_dangerous`,
              `6.13 SELF-KNOWLEDGE IS DANGEROUS`,
            ],
            [`6_14_confusion`, `6.14 CONFUSION`],
          ],
        },
        {
          title: `7 PROBLEMS AND GOALS`,
          path: `/text/7_problems_and_goals/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`7_1_intelligence`, `7.1 INTELLIGENCE`],
            [`7_2_uncommon_sense`, `7.2 UNCOMMON SENSE`],
            [`7_3_the_puzzle_principle`, `7.3 THE PUZZLE PRINCIPLE`],
            [`7_4_problem_solving`, `7.4 PROBLEM SOLVING`],
            [`7_5_learning_and_memory`, `7.5 LEARNING AND MEMORY`],
            [`7_6_reinforcement_and_reward`, `7.6 REINFORCEMENT AND REWARD`],
            [`7_7_local_responsibility`, `7.7 LOCAL RESPONSIBILITY`],
            [`7_8_difference-engines`, `7.8 DIFFERENCE-ENGINES`],
            [`7_9_intentions`, `7.9 INTENTIONS`],
            [`7_10_genius`, `7.10 GENIUS`],
          ],
        },
        {
          title: `8 A THEORY OF MEMORY`,
          path: `/text/8_a_theory_of_memory/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [
              `8_1_k-lines_a_theory_of_memory`,
              `8.1 K-LINES A THEORY OF MEMORY`,
            ],
            [`8_2_re-membering`, `8.2 RE-MEMBERING`],
            [
              `8_3_mental_states_and_dispositions`,
              `8.3 MENTAL STATES AND DISPOSITIONS`,
            ],
            [`8_4_partial_mental_states`, `8.4 PARTIAL MENTAL STATES`],
            [`8_5_level-bands`, `8.5 LEVEL-BANDS`],
            [`8_6_levels`, `8.6 LEVELS`],
            [`8_7_fringes`, `8.7 FRINGES`],
            [`8_8_societies_of_memories`, `8.8 SOCIETIES OF MEMORIES`],
            [`8_9_knowledge-trees`, `8.9 KNOWLEDGE-TREES`],
            [
              `8_10_levels_and_classifications`,
              `8.10 LEVELS AND CLASSIFICATIONS`,
            ],
            [`8_11_layers_of_societies`, `8.11 LAYERS OF SOCIETIES`],
          ],
        },

        {
          title: `9 SUMMARIES`,
          path: `/text/9_summaries`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`9_1_wanting_and_liking`, `9.1 WANTING AND LIKING`],
            [`9_2_gerrymandering`, `9.2 GERRYMANDERING`],
            [`9_3_learning_from_failure`, `9.3 LEARNING FROM FAILURE`],
            [`9_4_enjoying_discomfort`, `9.4 ENJOYING DISCOMFORT`],
          ],
        },
        {
          title: `10 PAPERTS PRINCIPLE`,
          path: `/text/10_paperts_principle/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`10_1_piagets_experiments`, `10.1 PIAGETS EXPERIMENTS`],
            [`10_2_reasoning_about_amounts`, `10.2 REASONING ABOUT AMOUNTS`],
            [`10_3_priorities`, `10.3 PRIORITIES`],
            [`10_4_paperts_principle`, `10.4 PAPERTS PRINCIPLE`],
            [`10_5_the_society-of-more`, `10.5 THE SOCIETY-OF-MORE`],
            [
              `10_6_about_piagets_experiments`,
              `10.6 ABOUT PIAGETS EXPERIMENTS`,
            ],
            [`10_7_the_concept_of_concept`, `10.7 THE CONCEPT OF CONCEPT`],
            [
              `10_8_education_and_development`,
              `10.8 EDUCATION AND DEVELOPMENT`,
            ],
            [`10_9_learning_a_hierarchy`, `10.9 LEARNING A HIERARCHY`],
          ],
        },
        {
          title: `11 THE SHAPE OF SPACE`,
          path: `/text/11_the_shape_of_space/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`11_1_seeing_red`, `11.1 SEEING RED`],
            [`11_2_the_shape_of_space`, `11.2 THE SHAPE OF SPACE`],
            [`11_3_nearnesses`, `11.3 NEARNESSES`],
            [`11_4_innate_geography`, `11.4 INNATE GEOGRAPHY`],
            [`11_5_sensing_similarities`, `11.5 SENSING SIMILARITIES`],
            [`11_6_the_centered_self`, `11.6 THE CENTERED SELF`],
            [`11_7_predestined_learning`, `11.7 PREDESTINED LEARNING`],
            [`11_8_half-brains`, `11.8 HALF-BRAINS`],
            [`11_9_dumbbell_theories`, `11.9 DUMBBELL THEORIES`],
          ],
        },
        {
          title: `12 LEARNING MEANING`,
          path: `/text/12_learning_meaning/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`12_1_a_block-arch_scenario`, `12.1 A BLOCK-ARCH SCENARIO`],
            [`12_2_learning_meaning`, `12.2 LEARNING MEANING`],
            [`12_3_uniframes`, `12.3 UNIFRAMES`],
            [`12_4_structure_and_function`, `12.4 STRUCTURE AND FUNCTION`],
            [
              `12_5_the_function_of_structures`,
              `12.5 THE FUNCTION OF STRUCTURES`,
            ],
            [`12_6_accumulation`, `12.6 ACCUMULATION`],
            [`12_7_accumulation_strategies`, `12.7 ACCUMULATION STRATEGIES`],
            [`12_8_problems_of_disunity`, `12.8 PROBLEMS OF DISUNITY`],
            [`12_9_the_exception_principle`, `12.9 THE EXCEPTION PRINCIPLE`],
            [`12_10_how_towers_work`, `12.10 HOW TOWERS WORK`],
            [`12_11_how_causes_work`, `12.11 HOW CAUSES WORK`],
            [`12_12_meaning_and_definition`, `12.12 MEANING AND DEFINITION`],
            [`12_13_bridge-definitions`, `12.13 BRIDGE-DEFINITIONS`],
          ],
        },
        {
          title: `13 SEEING AND BELIEVING`,
          path: `/text/13_seeing_and_believing/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`13_1_reformulation`, `13.1 REFORMULATION`],
            [`13_2_boundaries`, `13.2 BOUNDARIES`],
            [`13_3_seeing_and_believing`, `13.3 SEEING AND BELIEVING`],
            [`13_4_childrens_drawing-frames`, `13.4 CHILDRENS DRAWING-FRAMES`],
            [`13_5_learning_a_script`, `13.5 LEARNING A SCRIPT`],
            [`13_6_the_frontier_effect`, `13.6 THE FRONTIER EFFECT`],
            [`13_7_duplications`, `13.7 DUPLICATIONS`],
          ],
        },
        {
          title: `14 REFORMULATION`,
          path: `/text/14_reformulation/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`14_1_using_reformulation`, `14.1 USING REFORMULATION`],
            [`14_2_means_and_ends`, `14.2 MEANS AND ENDS`],
            [`14_3_seeing_squares`, `14.3 SEEING SQUARES`],
            [`14_4_brainstorming`, `14.4 BRAINSTORMING`],
            [`14_5_the_investment_principle`, `14.5 THE INVESTMENT PRINCIPLE`],
            [`14_6_parts_and_holes`, `14.6 PARTS AND HOLES`],
            [
              `14_7_the_power_of_negative_thinking`,
              `14.7 THE POWER OF NEGATIVE THINKING`,
            ],
            [`14_8_the_interaction-square`, `14.8 THE INTERACTION-SQUARE`],
          ],
        },
        {
          title: `15 CONSCIOUSNESS AND MEMORY`,
          path: `/text/15_consciousness_and_memory/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`15_1_momentary_mental_state`, `15.1 MOMENTARY MENTAL STATE`],
            [`15_2_self-examination`, `15.2 SELF-EXAMINATION`],
            [`15_3_memory`, `15.3 MEMORY`],
            [`15_4_memories_of_memories`, `15.4 MEMORIES OF MEMORIES`],
            [`15_5_the_immanence_illusion`, `15.5 THE IMMANENCE ILLUSION`],
            [`15_6_many_kinds_of_memory`, `15.6 MANY KINDS OF MEMORY`],
            [`15_7_memory_rearrangements`, `15.7 MEMORY REARRANGEMENTS`],
            [`15_8_anatomy_of_memory`, `15.8 ANATOMY OF MEMORY`],
            [
              `15_9_interruption_and_recovery`,
              `15.9 INTERRUPTION AND RECOVERY`,
            ],
            [`15_10_losing_track`, `15.10 LOSING TRACK`],
            [`15_11_the_recursion_principle`, `15.11 THE RECURSION PRINCIPLE`],
          ],
        },
        {
          title: `16 EMOTION`,
          path: `/text/16_emotion/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`16_1_emotion`, `16.1 EMOTION`],
            [`16_2_mental_growth`, `16.2 MENTAL GROWTH`],
            [`16_3_mental_proto-specialists`, `16.3 MENTAL PROTO-SPECIALISTS`],
            [`16_4_cross-exclusion`, `16.4 CROSS-EXCLUSION`],
            [`16_5_avalanche_effects`, `16.5 AVALANCHE EFFECTS`],
            [`16_6_motivation`, `16.6 MOTIVATION`],
            [`16_7_exploitation`, `16.7 EXPLOITATION`],
            [`16_8_stimulus_vs_simulus`, `16.8 STIMULUS VS. SIMULUS`],
            [`16_9_infant_emotions`, `16.9 INFANT EMOTIONS`],
            [`16_10_adult_emotions`, `16.10 ADULT EMOTIONS`],
          ],
        },
        {
          title: `17 DEVELOPMENT`,
          path: `/text/17_development/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [
              `17_1_sequences_of_teaching-selves`,
              `17.1 SEQUENCES OF TEACHING-SELVES`,
            ],
            [`17_2_attachment-learning`, `17.2 ATTACHMENT-LEARNING`],
            [`17_3_attachment_simplifies`, `17.3 ATTACHMENT SIMPLIFIES`],
            [`17_4_functional_autonomy`, `17.4 FUNCTIONAL AUTONOMY`],
            [`17_5_developmental_stages`, `17.5 DEVELOPMENTAL STAGES`],
            [`17_6_prerequisites_for_growth`, `17.6 PREREQUISITES FOR GROWTH`],
            [`17_7_genetic_timetables`, `17.7 GENETIC TIMETABLES`],
            [`17_8_attachment-images`, `17.8 ATTACHMENT-IMAGES`],
            [
              `17_9_different_spans_of_memories`,
              `17.9 DIFFERENT SPANS OF MEMORIES`,
            ],
            [`17_10_intellectual_trauma`, `17.10 INTELLECTUAL TRAUMA`],
            [`17_11_intellectual_ideals`, `17.11 INTELLECTUAL IDEALS`],
          ],
        },
        {
          title: `18 REASONING`,
          path: `/text/18_reasoning/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`18_1_must_machines_be_logical`, `18.1 MUST MACHINES BE LOGICAL`],
            [`18_2_chains_of_reasoning`, `18.2 CHAINS OF REASONING`],
            [`18_3_chaining`, `18.3 CHAINING`],
            [`18_4_logical_chains`, `18.4 LOGICAL CHAINS`],
            [`18_5_strong_arguments`, `18.5 STRONG ARGUMENTS`],
            [`18_6_magnitude_from_multitude`, `18.6 MAGNITUDE FROM MULTITUDE`],
            [`18_7_what_is_a_number`, `18.7 WHAT IS A NUMBER`],
            [`18_8_mathematics_made_hard`, `18.8 MATHEMATICS MADE HARD`],
            [`18_9_robustness_and_recovery`, `18.9 ROBUSTNESS AND RECOVERY`],
          ],
        },
        {
          title: `19 WORDS AND IDEAS`,
          path: `/text/19_words_and_ideas/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`19_1_the_roots_of_intention`, `19.1 THE ROOTS OF INTENTION`],
            [`19_2_the_language-agency`, `19.2 THE LANGUAGE-AGENCY`],
            [`19_3_words_and_ideas`, `19.3 WORDS AND IDEAS`],
            [`19_4_objects_and_properties`, `19.4 OBJECTS AND PROPERTIES`],
            [`19_5_polynemes`, `19.5 POLYNEMES`],
            [`19_6_recognizers`, `19.6 RECOGNIZERS`],
            [`19_7_weighing_evidence`, `19.7 WEIGHING EVIDENCE`],
            [`19_8_generalizing`, `19.8 GENERALIZING`],
            [`19_9_recognizing_thoughts`, `19.9 RECOGNIZING THOUGHTS`],
            [`19_10_closing_the_ring`, `19.10 CLOSING THE RING`],
          ],
        },
        {
          title: `20 CONTEXT AND AMBIGUITY`,
          path: `/text/20_context_and_ambiguity/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`20_1_ambiguity`, `20.1 AMBIGUITY`],
            [`20_2_negotiating_ambiguity`, `20.2 NEGOTIATING AMBIGUITY`],
            [`20_3_visual_ambiguity`, `20.3 VISUAL AMBIGUITY`],
            [
              `20_4_locking-in_and_weeding-out`,
              `20.4 LOCKING-IN AND WEEDING-OUT`,
            ],
            [`20_5_micronemes`, `20.5 MICRONEMES`],
            [`20_6_the_nemeic_spiral`, `20.6 THE NEMEIC SPIRAL`],
            [`20_7_connections`, `20.7 CONNECTIONS`],
            [`20_8_connection_lines`, `20.8 CONNECTION LINES`],
            [`20_9_distributed_memory`, `20.9 DISTRIBUTED MEMORY`],
          ],
        },
        {
          title: `21 TRANS-FRAMES`,
          path: `/text/21_trans-frames/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`21_1_the_pronouns_of_the_mind`, `21.1 THE PRONOUNS OF THE MIND`],
            [`21_2_pronomes`, `21.2 PRONOMES`],
            [`21_3_trans-frames`, `21.3 TRANS-FRAMES`],
            [
              `21_4_communication_among_agents`,
              `21.4 COMMUNICATION AMONG AGENTS`,
            ],
            [`21_5_automatism`, `21.5 AUTOMATISM`],
            [`21_6_trans-frame_pronomes`, `21.6 TRANS-FRAME PRONOMES`],
            [
              `21_7_generalizing_with_pronomes`,
              `21.7 GENERALIZING WITH PRONOMES`,
            ],
            [`21_8_attention`, `21.8 ATTENTION`],
          ],
        },
        {
          title: `22 EXPRESSION`,
          path: `/text/22_expression/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`22_1_pronomes_and_polynemes`, `22.1 PRONOMES AND POLYNEMES`],
            [`22_2_isonomes`, `22.2 ISONOMES`],
            [`22_3_de-specializing`, `22.3 DE-SPECIALIZING`],
            [`22_4_learning_and_teaching`, `22.4 LEARNING AND TEACHING`],
            [`22_5_inference`, `22.5 INFERENCE`],
            [`22_6_expression`, `22.6 EXPRESSION`],
            [`22_7_causes_and_clauses`, `22.7 CAUSES AND CLAUSES`],
            [`22_8_interruptions`, `22.8 INTERRUPTIONS`],
            [`22_9_pronouns_and_references`, `22.9 PRONOUNS AND REFERENCES`],
            [`22_10_verbal_expression`, `22.10 VERBAL EXPRESSION`],
            [`22_11_creative_expression`, `22.11 CREATIVE EXPRESSION`],
            [`23_1_a_world_of_differences`, `23.1 A WORLD OF DIFFERENCES`],
            [
              `23_2_differences_and_duplicates`,
              `23.2 DIFFERENCES AND DUPLICATES`,
            ],
            [`23_3_time_blinking`, `23.3 TIME BLINKING`],
            [`23_4_the_meanings_of_more`, `23.4 THE MEANINGS OF MORE`],
            [`23_5_foreign_accents`, `23.5 FOREIGN ACCENTS`],
          ],
        },
        {
          title: `24 FRAMES`,
          path: `/text/24_frames/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`24_1_the_speed_of_thought`, `24.1 THE SPEED OF THOUGHT`],
            [`24_2_frames_of_mind`, `24.2 FRAMES OF MIND`],
            [`24_3_how_trans-frames_work`, `24.3 HOW TRANS-FRAMES WORK`],
            [`24_4_default_assumptions`, `24.4 DEFAULT ASSUMPTIONS`],
            [`24_5_nonverbal_reasoning`, `24.5 NONVERBAL REASONING`],
            [`24_6_direction-nemes`, `24.6 DIRECTION-NEMES`],
            [`24_7_picture-frames`, `24.7 PICTURE-FRAMES`],
            [`24_8_how_picture-frames_work`, `24.8 HOW PICTURE-FRAMES WORK`],
            [
              `24_9_recognizers_and_memorizers`,
              `24.9 RECOGNIZERS AND MEMORIZERS`,
            ],
          ],
        },
        {
          title: `25 FRAME ARRAYS`,
          path: `/text/25_frame_arrays/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`25_1_one_frame_at_a_time`, `25.1 ONE FRAME AT A TIME`],
            [`25_2_frame-arrays`, `25.2 FRAME-ARRAYS`],
            [`25_3_the_stationary_world`, `25.3 THE STATIONARY WORLD`],
            [`25_4_the_sense_of_continuity`, `25.4 THE SENSE OF CONTINUITY`],
            [`25_5_expectations`, `25.5 EXPECTATIONS`],
            [`25_6_the_frame_idea`, `25.6 THE FRAME IDEA`],
          ],
        },
        {
          title: `26 LANGUAGE-FRAMES`,
          path: `/text/26_language-frames/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`26_1_understanding_words`, `26.1 UNDERSTANDING WORDS`],
            [`26_2_understanding_stories`, `26.2 UNDERSTANDING STORIES`],
            [`26_3_sentence-frames`, `26.3 SENTENCE-FRAMES`],
            [`26_4_a_party-frame`, `26.4 A PARTY-FRAME`],
            [`26_5_story-frames`, `26.5 STORY-FRAMES`],
            [`26_6_sentence_and_nonsense`, `26.6 SENTENCE AND NONSENSE`],
            [`26_7_frames_for_nouns`, `26.7 FRAMES FOR NOUNS`],
            [`26_8_frames_for_verbs`, `26.8 FRAMES FOR VERBS`],
            [`26_9_language_and_vision`, `26.9 LANGUAGE AND VISION`],
            [`26_10_learning_language`, `26.10 LEARNING LANGUAGE`],
            [`26_11_grammar`, `26.11 GRAMMAR`],
            [`26_12_coherent_discourse`, `26.12 COHERENT DISCOURSE`],
            [`27_1_demons`, `27.1 DEMONS`],
            [`27_2_suppressors`, `27.2 SUPPRESSORS`],
            [`27_3_censors`, `27.3 CENSORS`],
            [`27_4_exceptions_to_logic`, `27.4 EXCEPTIONS TO LOGIC`],
            [`27_5_jokes`, `27.5 JOKES`],
            [`27_6_humor_and_censorship`, `27.6 HUMOR AND CENSORSHIP`],
            [`27_7_laughter`, `27.7 LAUGHTER`],
            [`27_8_good_humor`, `27.8 GOOD HUMOR`],
          ],
        },
        {
          title: `28 THE MIND AND THE WORLD`,
          path: `/text/28_the_mind_and_the_world/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [
              `28_1_the_myth_of_mental_energy`,
              `28.1 THE MYTH OF MENTAL ENERGY`,
            ],
            [
              `28_2_magnitude_and_marketplace`,
              `28.2 MAGNITUDE AND MARKETPLACE`,
            ],
            [`28_3_quantity_and_quality`, `28.3 QUANTITY AND QUALITY`],
            [`28_4_mind_over_matter`, `28.4 MIND OVER MATTER`],
            [`28_5_the_mind_and_the_world`, `28.5 THE MIND AND THE WORLD`],
            [`28_6_minds_and_machines`, `28.6 MINDS AND MACHINES`],
            [`28_7_individual_identities`, `28.7 INDIVIDUAL IDENTITIES`],
            [`28_8_overlapping_minds`, `28.8 OVERLAPPING MINDS`],
          ],
        },
        {
          title: `29 THE REALMS OF THOUGHT`,
          path: `/text/29_the_realms_of_thought/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`29_1_the_realms_of_thought`, `29.1 THE REALMS OF THOUGHT`],
            [`29_2_several_thoughts_at_once`, `29.2 SEVERAL THOUGHTS AT ONCE`],
            [`29_3_paranomes`, `29.3 PARANOMES`],
            [
              `29_4_cross-realm_correspondences`,
              `29.4 CROSS-REALM CORRESPONDENCES`,
            ],
            [`29_5_the_problem_of_unity`, `29.5 THE PROBLEM OF UNITY`],
            [`29_6_autistic_children`, `29.6 AUTISTIC CHILDREN`],
            [`29_7_likenesses_and_analogies`, `29.7 LIKENESSES AND ANALOGIES`],
            [`29_8_metaphors`, `29.8 METAPHORS`],
          ],
        },
        {
          title: `30 MENTAL MODELS`,
          path: `/text/30_mental_models/`,
          collapsable: false,
          sidebarDepth: 2,
          children: [
            [`30_1_knowing`, `30.1 KNOWING`],
            [`30_2_knowing_and_believing`, `30.2 KNOWING AND BELIEVING`],
            [`30_3_mental_models`, `30.3 MENTAL MODELS`],
            [`30_4_world_models`, `30.4 WORLD MODELS`],
            [`30_5_knowing_ourselves`, `30.5 KNOWING OURSELVES`],
            [`30_6_freedom_of_will`, `30.6 FREEDOM OF WILL`],
            [
              `30_7_the_myth_of_the_third_alternative`,
              `30.7 THE MYTH OF THE THIRD ALTERNATIVE`,
            ],
            [
              `30_8_intelligence_and_resourcefulness`,
              `30.8 INTELLIGENCE AND RESOURCEFULNESS`,
            ],
          ],
        },
      ],
    },
  },

  /**
   * Apply plugins，ref：https://v1.vuepress.vuejs.org/zh/plugin/
   */
  plugins: ["@vuepress/plugin-back-to-top", "@vuepress/plugin-medium-zoom"],
}
